### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by mythodeia** [500px/greedo-layout-for-ios#11]
Hello
when i start in either portrait or landscape the layout is correct. When i rotate the device the images lose their insets

**Comment by mikewalkerjr** [comment]
I had a similar issue. What worked for me is within 

    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator)

I used the following lines:

    coordinator.animate(alongsideTransition: { (UIViewControllerTransitionCoordinatorContext) -> Void in                
    }, completion: { (UIViewControllerTransitionCoordinatorContext) -> Void in
        self.collectionViewSizeCalculator.clearCache()
        self.collectionViewSizeCalculator.rowMaximumHeight = size.height / 3
        self.collectionViewSizeCalculator.fixedHeight = false
                
        self.collectionView.performBatchUpdates(nil, completion: { (_) -> Void in
        })
    })

The line `self.collectionViewSizeCalculator.clearCache()` seems to have the desired effect.

**Comment by mythodeia** [comment]
@mikewalkerjr thanks
