### ISSUE TITLE
Cannot install Pods for example project

### ISSUE THREAD

**Issue by mohpor** [500px/greedo-layout-for-ios#5]
Hi,
I was going to run the example project, but when tried to install pods, it complains about my permission to your repo:

> [!] Error installing GreedoLayout
> [!] /usr/bin/git clone git@github.com:500px/greedo-layout-for-ios.git /var/folders/hv/zpcskz697xlfv17ktr6vtmjh0000gp/T/d20160227-1232-zb0mvp --single-branch --depth 1
> 
> Cloning into '/var/folders/hv/zpcskz697xlfv17ktr6vtmjh0000gp/T/d20160227-1232-zb0mvp'...
> Permission denied (publicly).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
>

**Comment by mythodeia** [comment]
same here

**Comment by beltex** [comment]
Hello @mohpor & @mythodeia!

Do you have an [SSH key setup with GitHub](https://help.github.com/articles/generating-an-ssh-key/)? That seems to be the issue, since the Podfile is using the SSH URL to the repository. Should work if you replace it with the HTTPS one (`https://github.com/500px/greedo-layout-for-ios.git`).

**Comment by mythodeia** [comment]
:+1:

**Comment by mohpor** [comment]
tnx

> On Feb 28 2016, at 12:52 am, Konstantinos K.
&lt;notifications@github.com&gt; wrote:  

>

> ![:+1:](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/500px
/greedo-layout-for-ios/issues/5#issuecomment-189728822).![](https://github.com
/notifications/beacon/AEuZ3B12YgY3SNUQZLhdPuoSg21aX9vFks5pogr8gaJpZM4HkYV1.gif
)
